// <auto-generated />
using System;
using Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Entity.Model.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Ataque")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Defensa")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Poder")
                        .HasColumnType("int");

                    b.Property<int>("Terror")
                        .HasColumnType("int");

                    b.Property<int>("Velocidad")
                        .HasColumnType("int");

                    b.Property<int>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .IsUnique();

                    b.ToTable("Cartas");
                });

            modelBuilder.Entity("Entity.Model.CartaJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdCarta")
                        .HasColumnType("int");

                    b.Property<int>("IdJugada")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.Property<bool>("Usada")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdCarta");

                    b.HasIndex("IdJugador");

                    b.ToTable("CartaJugadores");
                });

            modelBuilder.Entity("Entity.Model.Jugada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdCartaJugador")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.Property<int>("IdRonda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCartaJugador");

                    b.HasIndex("IdJugador");

                    b.HasIndex("IdRonda");

                    b.ToTable("Jugadas");
                });

            modelBuilder.Entity("Entity.Model.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int>("PosicionTurno")
                        .HasColumnType("int");

                    b.Property<int>("PuntosAcumulados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Entity.Model.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RondasJugadas")
                        .HasColumnType("int");

                    b.Property<DateTime>("TiempoPartida")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("Entity.Model.Ronda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AtributoCompetido")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdGanador")
                        .HasColumnType("int");

                    b.Property<int>("IdJugada")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador")
                        .HasColumnType("int");

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.Property<int>("NumeroRonda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGanador");

                    b.HasIndex("IdPartida");

                    b.ToTable("Rondas");
                });

            modelBuilder.Entity("Entity.Model.CartaJugador", b =>
                {
                    b.HasOne("Entity.Model.Carta", "Carta")
                        .WithMany("CartaJugador")
                        .HasForeignKey("IdCarta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Model.Jugador", "Jugador")
                        .WithMany("CartaJugador")
                        .HasForeignKey("IdJugador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Entity.Model.Jugada", b =>
                {
                    b.HasOne("Entity.Model.CartaJugador", "CartaJugador")
                        .WithMany("Jugada")
                        .HasForeignKey("IdCartaJugador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entity.Model.Jugador", "Jugador")
                        .WithMany("Jugada")
                        .HasForeignKey("IdJugador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entity.Model.Ronda", "Ronda")
                        .WithMany("Jugada")
                        .HasForeignKey("IdRonda")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CartaJugador");

                    b.Navigation("Jugador");

                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("Entity.Model.Jugador", b =>
                {
                    b.HasOne("Entity.Model.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Entity.Model.Ronda", b =>
                {
                    b.HasOne("Entity.Model.Jugador", "Jugador")
                        .WithMany("Ronda")
                        .HasForeignKey("IdGanador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entity.Model.Partida", "Partida")
                        .WithMany("Ronda")
                        .HasForeignKey("IdPartida")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Entity.Model.Carta", b =>
                {
                    b.Navigation("CartaJugador");
                });

            modelBuilder.Entity("Entity.Model.CartaJugador", b =>
                {
                    b.Navigation("Jugada");
                });

            modelBuilder.Entity("Entity.Model.Jugador", b =>
                {
                    b.Navigation("CartaJugador");

                    b.Navigation("Jugada");

                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("Entity.Model.Partida", b =>
                {
                    b.Navigation("Ronda");
                });

            modelBuilder.Entity("Entity.Model.Ronda", b =>
                {
                    b.Navigation("Jugada");
                });
#pragma warning restore 612, 618
        }
    }
}
